#!/bin/bash
mkdir root/alx-system_engineering-devops/0x00-shell_basics/welcome | mkdir root/alx-system_engineering-devops/0x00-shell_basics/welcome/to | mkdir root/alx-system_engineering-devops/0x00-shell_basics/welcome/to/school 
